// Copyright Epic Games, Inc. All Rights Reserved.

#include "WFC/Example/WFC3DAsyncExample.h"
#include "Engine/Engine.h"
#include "Async/Async.h"
#include "Async/TaskGraphInterfaces.h"
#include "WFC/Data/WFC3DGrid.h"

AWFC3DAsyncExample::AWFC3DAsyncExample()
{
	PrimaryActorTick.bCanEverTick = false;

	// WFC ì•Œê³ ë¦¬ì¦˜ ì¸ìŠ¤í„´ìŠ¤ ìƒì„±
	WFCAlgorithm = CreateDefaultSubobject<UWFC3DAlgorithm>(TEXT("WFCAlgorithm"));
}

void AWFC3DAsyncExample::BeginPlay()
{
	Super::BeginPlay();

	UE_LOG(LogTemp, Error, TEXT("Begin Play: WFC3DAsyncExample ì‹œì‘"));

	// ë¸ë¦¬ê²Œì´íŠ¸ ë°”ì¸ë”©
	if (WFCAlgorithm)
	{
		UE_LOG(LogTemp, Display, TEXT("Add Delegates to WFCAlgorithm"));
		WFCAlgorithm->OnAlgorithmCompleted.AddDynamic(this, &AWFC3DAsyncExample::OnAlgorithmCompleted);
		WFCAlgorithm->OnAlgorithmCancelled.AddDynamic(this, &AWFC3DAsyncExample::OnAlgorithmCancelled);
		WFCAlgorithm->OnAlgorithmProgress.AddDynamic(this, &AWFC3DAsyncExample::OnAlgorithmProgress);
	}

	// ì•Œê³ ë¦¬ì¦˜ ì»¨í…ìŠ¤íŠ¸ ì„¤ì • Grid í¬ê¸° (5,5,5)
	AlgorithmContext.Grid = NewObject<UWFC3DGrid>();

	ExecuteAsync();
}

void AWFC3DAsyncExample::ExecuteSync()
{
	if (!WFCAlgorithm)
	{
		UE_LOG(LogTemp, Error, TEXT("WFCAlgorithm is null"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("=== ë™ê¸° ì‹¤í–‰ ì‹œì‘ (ë©”ì¸ ìŠ¤ë ˆë“œ) ==="));

	// ë©”ì¸ ìŠ¤ë ˆë“œì—ì„œ ë™ê¸°ì ìœ¼ë¡œ ì‹¤í–‰
	FWFC3DResult Result = WFCAlgorithm->Execute(AlgorithmContext);

	if (Result.bSuccess)
	{
		UE_LOG(LogTemp, Log, TEXT("ë™ê¸° ì‹¤í–‰ ì™„ë£Œ! ê²°ê³¼: ì„±ê³µ"));
	}
	else
	{
		UE_LOG(LogTemp, Warning, TEXT("ë™ê¸° ì‹¤í–‰ ì™„ë£Œ! ê²°ê³¼: ì‹¤íŒ¨"));
	}
}

void AWFC3DAsyncExample::ExecuteAsync()
{
	if (!WFCAlgorithm)
	{
		UE_LOG(LogTemp, Error, TEXT("WFCAlgorithm is null"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("=== ë¹„ë™ê¸° ì‹¤í–‰ ì‹œì‘ (FAsyncTask ì‚¬ìš©) ==="));

	// í…ŒìŠ¤íŠ¸ìš© Grid ìƒì„± ë° ì´ˆê¸°í™”
	UWFC3DGrid* TestGrid = NewObject<UWFC3DGrid>();
	TestGrid->InitializeGrid({TestGridSize.X, TestGridSize.Y, TestGridSize.Z}, TestModelData); // 555 ê·¸ë¦¬ë“œë¡œ í…ŒìŠ¤íŠ¸

	// ì»¨í…ìŠ¤íŠ¸ ìƒì„±
	FWFC3DAlgorithmContext TestContext(TestGrid, TestModelData);
	AlgorithmContext = TestContext;
	
	UE_LOG(LogTemp, Warning, TEXT("ğŸ§ª í…ŒìŠ¤íŠ¸ ì»¨í…ìŠ¤íŠ¸ ìƒì„±ë¨"));
	UE_LOG(LogTemp, Warning, TEXT("Grid: %s"), TestGrid ? TEXT("Valid") : TEXT("Invalid"));
	UE_LOG(LogTemp, Warning, TEXT("Grid Dimension: %s"), *TestGrid->GetDimension().ToString());
	UE_LOG(LogTemp, Warning, TEXT("Grid Remaining Cells: %d"), TestGrid->GetRemainingCells());

	// ì§„í–‰ë¥  í‘œì‹œ íƒ€ì´ë¨¸ ì‹œì‘
	GetWorldTimerManager().SetTimer(
		ProgressTimerHandle,
		this,
		&AWFC3DAsyncExample::ShowProgress,
		0.5f, // 0.5ì´ˆë§ˆë‹¤
		true
	);
	
	// ë¹„ë™ê¸° ì‹¤í–‰
	WFCAlgorithm->ExecuteAsync(AlgorithmContext);
}

void AWFC3DAsyncExample::ExecuteWithTaskGraph()
{
	if (!WFCAlgorithm)
	{
		UE_LOG(LogTemp, Error, TEXT("WFCAlgorithm is null"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("=== Task Graphë¥¼ ì‚¬ìš©í•œ ë¹„ë™ê¸° ì‹¤í–‰ ì‹œì‘ ==="));

	// Task Graphë¥¼ ì‚¬ìš©í•œ ë¹„ë™ê¸° ì‹¤í–‰
	AsyncTask(ENamedThreads::AnyBackgroundThreadNormalTask, [this]()
	{
		// ë°±ê·¸ë¼ìš´ë“œ ìŠ¤ë ˆë“œì—ì„œ ì‹¤í–‰
		FWFC3DResult Result = WFCAlgorithm->ExecuteInternal(AlgorithmContext);

		// ë©”ì¸ ìŠ¤ë ˆë“œì—ì„œ ê²°ê³¼ ì²˜ë¦¬
		AsyncTask(ENamedThreads::GameThread, [this, Result]()
		{
			OnTaskGraphCompleted(Result);
		});
	});
}

void AWFC3DAsyncExample::ExecuteWithThreadPool()
{
	if (!WFCAlgorithm)
	{
		UE_LOG(LogTemp, Error, TEXT("WFCAlgorithm is null"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("=== Thread Poolì„ ì‚¬ìš©í•œ ë¹„ë™ê¸° ì‹¤í–‰ ì‹œì‘ ==="));

	// Thread Poolì„ ì‚¬ìš©í•œ ë¹„ë™ê¸° ì‹¤í–‰
	Async(EAsyncExecution::ThreadPool, [this]()
	{
		// Thread Poolì—ì„œ ì‹¤í–‰
		FWFC3DResult Result = WFCAlgorithm->ExecuteInternal(AlgorithmContext);

		// ë©”ì¸ ìŠ¤ë ˆë“œì—ì„œ ê²°ê³¼ ì²˜ë¦¬
		Async(EAsyncExecution::TaskGraphMainThread, [this, Result]()
		{
			OnThreadPoolCompleted(Result);
		});
	});
}

void AWFC3DAsyncExample::CancelExecution()
{
	if (!WFCAlgorithm)
	{
		UE_LOG(LogTemp, Error, TEXT("WFCAlgorithm is null"));
		return;
	}

	UE_LOG(LogTemp, Warning, TEXT("=== ì‹¤í–‰ ì·¨ì†Œ ìš”ì²­ ==="));
	WFCAlgorithm->CancelExecution();
}

void AWFC3DAsyncExample::CheckStatus()
{
	if (!WFCAlgorithm)
	{
		UE_LOG(LogTemp, Error, TEXT("WFCAlgorithm is null"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("=== í˜„ì¬ ìƒíƒœ ==="));
	UE_LOG(LogTemp, Log, TEXT("ì‹¤í–‰ ì¤‘: %s"), WFCAlgorithm->IsRunning() ? TEXT("ì˜ˆ") : TEXT("ì•„ë‹ˆì˜¤"));
	UE_LOG(LogTemp, Log, TEXT("ì·¨ì†Œë¨: %s"), WFCAlgorithm->IsCancelled() ? TEXT("ì˜ˆ") : TEXT("ì•„ë‹ˆì˜¤"));
	UE_LOG(LogTemp, Log, TEXT("ì™„ë£Œë¨: %s"), WFCAlgorithm->IsComplete() ? TEXT("ì˜ˆ") : TEXT("ì•„ë‹ˆì˜¤"));
	UE_LOG(LogTemp, Log, TEXT("ì§„í–‰ë¥ : %.1f%%"), WFCAlgorithm->GetProgress() * 100.0f);
}

void AWFC3DAsyncExample::OnAlgorithmCompleted(const FWFC3DResult& Result)
{
	// ì§„í–‰ë¥  íƒ€ì´ë¨¸ ì •ë¦¬
	GetWorldTimerManager().ClearTimer(ProgressTimerHandle);

	UE_LOG(LogTemp, Log, TEXT("=== ì•Œê³ ë¦¬ì¦˜ ì™„ë£Œ! ==="));
	UE_LOG(LogTemp, Log, TEXT("ì„±ê³µ: %s"), Result.bSuccess ? TEXT("ì˜ˆ") : TEXT("ì•„ë‹ˆì˜¤"));
	UE_LOG(LogTemp, Log, TEXT("Collapse ê²°ê³¼ ìˆ˜: %d"), Result.CollapseResults.Num());
	UE_LOG(LogTemp, Log, TEXT("Propagation ê²°ê³¼ ìˆ˜: %d"), Result.PropagationResults.Num());
	
	// í™”ë©´ì— ë©”ì‹œì§€ í‘œì‹œ
	if (GEngine)
	{
		GEngine->AddOnScreenDebugMessage(
			-1, 5.0f, FColor::Green,
			FString::Printf(TEXT("WFC ì•Œê³ ë¦¬ì¦˜ ì™„ë£Œ! ì„±ê³µ: %s"),
			                Result.bSuccess ? TEXT("ì˜ˆ") : TEXT("ì•„ë‹ˆì˜¤"))
		);
	}
}

void AWFC3DAsyncExample::OnAlgorithmCancelled()
{
	// ì§„í–‰ë¥  íƒ€ì´ë¨¸ ì •ë¦¬
	GetWorldTimerManager().ClearTimer(ProgressTimerHandle);

	UE_LOG(LogTemp, Warning, TEXT("=== ì•Œê³ ë¦¬ì¦˜ ì·¨ì†Œë¨! ==="));

	// í™”ë©´ì— ë©”ì‹œì§€ í‘œì‹œ
	if (GEngine)
	{
		GEngine->AddOnScreenDebugMessage(-1, 5.0f, FColor::Yellow, TEXT("WFC ì•Œê³ ë¦¬ì¦˜ì´ ì·¨ì†Œë˜ì—ˆìŠµë‹ˆë‹¤!"));
	}
}

void AWFC3DAsyncExample::OnAlgorithmProgress(int32 CurrentStep, int32 TotalSteps)
{
	float Progress = TotalSteps > 0 ? (float)CurrentStep / (float)TotalSteps * 100.0f : 0.0f;

	UE_LOG(LogTemp, Log, TEXT("ì§„í–‰ë¥ : %d/%d (%.1f%%)"), CurrentStep, TotalSteps, Progress);

	// í™”ë©´ì— ì§„í–‰ë¥  í‘œì‹œ
	if (GEngine)
	{
		GEngine->AddOnScreenDebugMessage(
			1, 1.0f, FColor::Blue,
			FString::Printf(TEXT("ì§„í–‰ë¥ : %d/%d (%.1f%%)"), CurrentStep, TotalSteps, Progress)
		);
	}
}

void AWFC3DAsyncExample::ShowProgress()
{
	if (WFCAlgorithm)
	{
		float Progress = WFCAlgorithm->GetProgress() * 100.0f;

		if (GEngine)
		{
			GEngine->AddOnScreenDebugMessage(
				2, 1.0f, FColor::Cyan,
				FString::Printf(TEXT("í˜„ì¬ ì§„í–‰ë¥ : %.1f%%"), Progress)
			);
		}
	}
}

void AWFC3DAsyncExample::OnTaskGraphCompleted(FWFC3DResult Result)
{
	UE_LOG(LogTemp, Log, TEXT("=== Task Graph ì‹¤í–‰ ì™„ë£Œ! ==="));
	UE_LOG(LogTemp, Log, TEXT("ì„±ê³µ: %s"), Result.bSuccess ? TEXT("ì˜ˆ") : TEXT("ì•„ë‹ˆì˜¤"));

	if (GEngine)
	{
		GEngine->AddOnScreenDebugMessage(
			-1, 5.0f, FColor::Purple,
			FString::Printf(TEXT("Task Graph ì™„ë£Œ! ì„±ê³µ: %s"),
			                Result.bSuccess ? TEXT("ì˜ˆ") : TEXT("ì•„ë‹ˆì˜¤"))
		);
	}
}

void AWFC3DAsyncExample::OnThreadPoolCompleted(FWFC3DResult Result)
{
	UE_LOG(LogTemp, Log, TEXT("=== Thread Pool ì‹¤í–‰ ì™„ë£Œ! ==="));
	UE_LOG(LogTemp, Log, TEXT("ì„±ê³µ: %s"), Result.bSuccess ? TEXT("ì˜ˆ") : TEXT("ì•„ë‹ˆì˜¤"));

	if (GEngine)
	{
		GEngine->AddOnScreenDebugMessage(
			-1, 5.0f, FColor::Orange,
			FString::Printf(TEXT("Thread Pool ì™„ë£Œ! ì„±ê³µ: %s"),
			                Result.bSuccess ? TEXT("ì˜ˆ") : TEXT("ì•„ë‹ˆì˜¤"))
		);
	}
}
